# Generated by Django 2.2.6 on 2019-11-14 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_desc', models.CharField(max_length=200)),
                ('job_date', models.DateTimeField(verbose_name='date of job')),
                ('job_booked', models.BooleanField()),
                ('job_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('job_installer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstallerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installer_date1', models.DateField(verbose_name='available date1')),
                ('installer_date2', models.DateField(verbose_name='available date2')),
                ('installer_date3', models.DateField(verbose_name='available date3')),
                ('installer_availability', models.CharField(max_length=200)),
                ('installer_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installer_alias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
