# Generated by Django 2.2.6 on 2019-11-17 19:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_installerdetails_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstallerDetails',
            new_name='InstallerDetail',
        ),
    ]
