# Generated by Django 2.2.6 on 2019-11-19 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191117_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='installerdetail',
            name='installer_skillset',
            field=models.CharField(choices=[('gas boiler installations', 'Gas Boiler Installations'), ('oil boiler installations', 'Oil Boiler Installations'), ('all boiler installations', 'All Boiler Installations'), ('heating control installations', 'Heating Control Installations'), ('gas boiler & heating control installations', 'Gas Boiler & Heating Control Installations'), ('oil boiler & heating control installations', 'Oil Boiler & Heating Control Installations'), ('all boiler & heating control installations', 'All Boiler & Heating Control Installations')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
