# Generated by Django 2.2.6 on 2019-11-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_installerdetail_installer_skillset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installerdetail',
            name='installer_skillset',
            field=models.CharField(choices=[('gas boiler installations', 'Gas Boiler Installations'), ('oil boiler installations', 'Oil Boiler Installations'), ('all boiler installations', 'All Boiler Installations'), ('heating control installations', 'Heating Control Installations'), ('gas boiler & heating control installations', 'Gas Boiler & Heating Control Installations'), ('oil boiler & heating control installations', 'Oil Boiler & Heating Control Installations'), ('all boiler & heating control installations', 'All Boiler & Heating Control Installations')], max_length=50),
        ),
    ]
