# Generated by Django 2.2.6 on 2019-11-19 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191119_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='installerdetail',
            name='installer_radius',
            field=models.CharField(choices=[('cork', 'Cork'), ('kerry', 'Kerry'), ('limerick', 'Limerick'), ('dublin', 'Dublin')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
