# Generated by Django 2.2.6 on 2020-02-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='boiler_and_heating_control_installations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='boiler_installations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='cork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='dublin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='heating_control_installations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='kerry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='limerick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='meath',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='waterford',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
