# Generated by Django 2.2.6 on 2020-02-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200215_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='monday',
            field=models.BooleanField(verbose_name='Monday'),
        ),
    ]
