# Generated by Django 2.2.6 on 2020-02-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jobType', models.CharField(max_length=50)),
                ('serviceableArea', models.CharField(max_length=50)),
            ],
        ),
    ]
