# Generated by Django 2.2.6 on 2020-02-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='boiler_and_heating_control_installations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='boiler_installations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='cork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='dublin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='heating_control_installations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='kerry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='limerick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='meath',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='waterford',
            field=models.BooleanField(default=False),
        ),
    ]
