# Generated by Django 2.2.6 on 2020-01-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('mobile', models.TextField()),
                ('address', models.TextField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
