# Generated by Django 2.2.6 on 2020-01-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Installers',
            new_name='Installer',
        ),
    ]
