# Generated by Django 2.2.6 on 2020-01-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0002_auto_20200124_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
