# Generated by Django 2.2.6 on 2020-02-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0004_auto_20200126_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installer',
            old_name='mobile',
            new_name='available_days',
        ),
        migrations.RenameField(
            model_name='installer',
            old_name='address',
            new_name='serviceable_areas',
        ),
        migrations.RenameField(
            model_name='installer',
            old_name='bio',
            new_name='skillset',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='email',
        ),
    ]
