# Generated by Django 2.2.6 on 2020-02-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0006_auto_20200201_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installer',
            name='available_days',
            field=models.BooleanField(default=False, verbose_name='Wednesday'),
        ),
    ]
