# Generated by Django 2.2.6 on 2020-02-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0007_auto_20200201_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installer',
            old_name='available_days',
            new_name='available_day3',
        ),
        migrations.AddField(
            model_name='installer',
            name='available_day1',
            field=models.BooleanField(default=False, verbose_name='Monday'),
        ),
        migrations.AddField(
            model_name='installer',
            name='available_day2',
            field=models.BooleanField(default=False, verbose_name='Tuesday'),
        ),
    ]
