# Generated by Django 2.2.6 on 2020-02-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0008_auto_20200201_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installer',
            name='available_day1',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='available_day2',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='available_day3',
        ),
    ]
