# Generated by Django 2.2.6 on 2020-02-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0010_installer_available_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installer',
            name='available_days',
        ),
        migrations.AddField(
            model_name='installer',
            name='monday',
            field=models.BooleanField(default=False),
        ),
    ]
