# Generated by Django 2.2.6 on 2020-02-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0012_auto_20200202_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installer',
            name='name',
        ),
        migrations.AddField(
            model_name='installer',
            name='boiler_and_heating_control_installations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installer',
            name='boiler_installations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installer',
            name='cork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installer',
            name='dublin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installer',
            name='heating_control_installations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installer',
            name='kerry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installer',
            name='limerick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installer',
            name='meath',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installer',
            name='waterford',
            field=models.BooleanField(default=False),
        ),
    ]
